### ISSUE TITLE
License and PyPI package

### ISSUE THREAD

**Issue by devanshkv** [telegraphic/numbits#3]
Hi!

We would like to use this package with our library called [your](https://github.com/thepetabyteproject/your).
Can you please add a license and, if possible, make it available via PyPI.

Thanks!

**Comment by telegraphic** [comment]
Hey @devanshkv -- agreed this should have a license. This has portions of code extracted from sigpyproc so dependent on that.

**Comment by telegraphic** [comment]
@ewanbarr would you be happy for this code to be licensed under MIT? (I've basically just wrapped the sigpyproc 1/2/4 bit unpack code with pybind11 so you can use it on numpy arrays)

**Comment by ewanbarr** [comment]
@telegraphic No objections from me.

**Comment by telegraphic** [comment]
Hooray, thanks Ewan 🎉
